import type { ToolInvocationKind } from '../../types/domain';
import type { ToolActionKind } from '../toolActionTypes';
import type {
  PolarisRegistryToolGroup,
  PolarisToolResultReplayMode
} from './toolRegistryShared';

export type PolarisToolExecutorPluginId =
  | 'app'
  | 'attachment'
  | 'code-card'
  | 'collection'
  | 'mcp'
  | 'theme'
  | 'utility'
  | 'web';

export type PolarisToolFallbackMetadata = {
  label: string;
  group?: PolarisRegistryToolGroup;
  executorPlugin?: PolarisToolExecutorPluginId;
  resultReplayMode?: PolarisToolResultReplayMode;
};

export const POLARIS_TOOL_EXECUTOR_BY_ACTION_KIND = {
  applyThemeCoordinates: 'theme',
  applySurfaceTokens: 'theme',
  patchRawCss: 'theme',
  readThemeCss: 'theme',
  editThemeCss: 'theme',
  appendThemeCss: 'theme',
  insertThemeCss: 'theme',
  deleteThemeCss: 'theme',
  replaceThemeCss: 'theme',
  inspectThemeRender: 'theme',
  applyPreset: 'theme',
  switchWorld: 'app',
  createRoomProject: 'collection',
  createCodeCard: 'collection',
  createProjectFile: 'collection',
  promoteCardToProject: 'collection',
  listCodeCards: 'collection',
  patchCodeCard: 'collection',
  appendCodeCard: 'collection',
  appendProjectFile: 'collection',
  insertProjectFile: 'collection',
  replaceProjectFileLines: 'collection',
  writeProjectFiles: 'collection',
  patchRoomProject: 'collection',
  listProjectFiles: 'collection',
  searchProjectFiles: 'collection',
  readWorkspacePreviewState: 'collection',
  listWorkspaceReferences: 'collection',
  searchWorkspaceReferences: 'collection',
  readWorkspaceReference: 'collection',
  promoteWorkspaceReferenceToProjectFile: 'collection',
  pinProjectFileAsReference: 'collection',
  checkProjectPreview: 'collection',
  inspectProjectRuntime: 'collection',
  editCodeCardText: 'collection',
  editProjectFileText: 'collection',
  deleteProjectFile: 'collection',
  readCodeCard: 'collection',
  readProjectFile: 'collection',
  readProjectFileContext: 'collection',
  writeMemory: 'utility',
  writeMemoryDoc: 'utility',
  readMemoryDoc: 'utility',
  searchMemory: 'utility',
  openMemorySource: 'utility',
  readPolarisKnowledge: 'utility',
  listEnvironmentNodes: 'utility',
  inspectEnvironmentNode: 'utility',
  searchEnvironmentNodes: 'utility',
  searchReadableContext: 'collection',
  startTask: 'utility',
  completeTask: 'utility',
  wait: 'utility',
  createProactiveMessageRule: 'utility',
  listProactiveMessageRules: 'utility',
  updateProactiveMessageRule: 'utility',
  deleteProactiveMessageRule: 'utility',
  inspectAttachments: 'attachment',
  webSearch: 'web',
  readWebPage: 'web',
  listCalendars: 'utility',
  readCalendarEvents: 'utility',
  createCalendarEvent: 'utility',
  updateCalendarEvent: 'utility',
  deleteCalendarEvent: 'utility',
  inspectArchiveEntries: 'attachment',
  readAttachmentText: 'attachment',
  readArchiveEntryText: 'attachment',
  bundleArchiveEntries: 'attachment',
  bundleAttachments: 'attachment',
  createQrCode: 'attachment',
  generateImage: 'attachment',
  sendImageAttachment: 'attachment',
  inspectImageAsset: 'attachment',
  extractImagePalette: 'attachment',
  createImageVariant: 'attachment',
  saveAttachmentToCollection: 'attachment',
  saveAttachmentAsCodeCard: 'attachment',
  saveArchiveEntryAsCodeCard: 'attachment',
  runAndroidShell: 'utility',
  runCode: 'utility',
  listDesktopWorkspaces: 'utility',
  listDesktopFiles: 'utility',
  readDesktopFile: 'utility',
  searchDesktopFiles: 'utility',
  readDesktopFileContext: 'utility',
  writeDesktopFile: 'utility',
  editDesktopFileText: 'utility',
  replaceDesktopFileLines: 'utility',
  createDesktopDirectory: 'utility',
  deleteDesktopPath: 'utility',
  moveDesktopPath: 'utility',
  runDesktopCommand: 'utility',
  runDesktopCommandSequence: 'utility',
  startDesktopCommand: 'utility',
  listDesktopCommandSessions: 'utility',
  stopDesktopCommand: 'utility',
  syncDesktopWorkspaceFromDisk: 'utility',
  syncDesktopWorkspaceToDisk: 'utility',
  invokeCodeCardTool: 'code-card',
  invokeMcpTool: 'mcp'
} satisfies Record<ToolActionKind, PolarisToolExecutorPluginId>;

export const POLARIS_TOOL_FALLBACK_METADATA: Record<ToolInvocationKind, PolarisToolFallbackMetadata> = {
  applyThemeCoordinates: { label: '整体坐标换肤' },
  applySurfaceTokens: { label: '单区域精修' },
  patchRawCss: { label: '创意 CSS 试穿' },
  readThemeCss: { label: '读取 theme.css' },
  editThemeCss: { label: '主题 CSS 精修' },
  appendThemeCss: { label: '主题 CSS 追加' },
  insertThemeCss: { label: '主题 CSS 插入' },
  deleteThemeCss: { label: '主题 CSS 删除' },
  replaceThemeCss: { label: '完整主题 CSS 试穿' },
  inspectThemeRender: { label: '主题渲染检查' },
  applyPreset: { label: '试穿主题预设' },
  switchWorld: { label: '世界切换' },
  createRoomProject: { label: '创建工作区' },
  saveCodeCard: { label: '保存卡片' },
  createCodeCard: { label: '创建卡片' },
  createProjectFile: { label: '创建工作区文件' },
  promoteCardToProject: { label: '升为工作区' },
  listCodeCards: { label: '读取房间卡目录' },
  patchCodeCard: { label: '更新房间' },
  appendCodeCard: { label: '续写房间' },
  appendProjectFile: { label: '续写工作区文件' },
  insertProjectFile: { label: '插入工作区文件' },
  replaceProjectFileLines: { label: '按行替换工作区文件' },
  writeProjectFiles: { label: '写入工作区文件' },
  patchRoomProject: { label: '更新工作区封面' },
  listProjectFiles: { label: '读取工作区目录' },
  searchProjectFiles: { label: '搜索工作区文件' },
  readWorkspacePreviewState: { label: '读取预览状态', resultReplayMode: 'full-detail' },
  listWorkspaceReferences: { label: '读取参考资料目录' },
  searchWorkspaceReferences: { label: '搜索参考资料' },
  readWorkspaceReference: { label: '读取参考资料' },
  promoteWorkspaceReferenceToProjectFile: { label: '参考资料转工作区文件' },
  pinProjectFileAsReference: { label: '工作区文件钉为参考资料' },
  checkProjectPreview: { label: '检查工作区预览' },
  inspectProjectRuntime: { label: '运行工作区预览' },
  editCodeCardText: { label: '局部替换房间' },
  editProjectFileText: { label: '局部替换工作区文件' },
  deleteProjectFile: { label: '删除工作区文件' },
  readCodeCard: { label: '读取房间' },
  readProjectFile: { label: '读取工作区文件' },
  readProjectFileContext: { label: '读取工作区上下文' },
  writeMemory: { label: '写入记忆' },
  writeMemoryDoc: { label: '写入长期资料' },
  readMemoryDoc: { label: '读取长期资料' },
  searchMemory: { label: '搜索过往记忆', resultReplayMode: 'full-detail' },
  openMemorySource: { label: '打开记忆原文', resultReplayMode: 'full-detail' },
  readPolarisKnowledge: { label: '读取 Polaris 产品知识' },
  listEnvironmentNodes: { label: '列出环境目录', group: 'environment', resultReplayMode: 'detail-excerpt' },
  inspectEnvironmentNode: { label: '检查环境节点', group: 'environment', resultReplayMode: 'detail-excerpt' },
  searchEnvironmentNodes: { label: '搜索环境目录', group: 'environment', resultReplayMode: 'detail-excerpt' },
  searchReadableContext: { label: '搜索可读上下文' },
  startTask: { label: '开启任务' },
  completeTask: { label: '完成任务' },
  wait: { label: '等待轮询', group: 'task', resultReplayMode: 'detail-excerpt' },
  createProactiveMessageRule: { label: '创建主动消息规则', group: 'proactive', resultReplayMode: 'detail-excerpt' },
  listProactiveMessageRules: { label: '查看主动消息规则', group: 'proactive', resultReplayMode: 'full-detail' },
  updateProactiveMessageRule: { label: '修改主动消息规则', group: 'proactive', resultReplayMode: 'detail-excerpt' },
  deleteProactiveMessageRule: { label: '取消主动消息规则', group: 'proactive', resultReplayMode: 'detail-excerpt' },
  inspectAttachments: { label: '检查附件' },
  webSearch: { label: '联网搜索' },
  readWebPage: { label: '读取网页' },
  listCalendars: { label: '读取可写日历', group: 'personalData', resultReplayMode: 'full-detail' },
  readCalendarEvents: { label: '读取系统日历', group: 'personalData', resultReplayMode: 'full-detail' },
  createCalendarEvent: { label: '创建系统日程', group: 'personalData', resultReplayMode: 'full-detail' },
  updateCalendarEvent: { label: '修改系统日程', group: 'personalData', resultReplayMode: 'full-detail' },
  deleteCalendarEvent: { label: '删除系统日程', group: 'personalData', resultReplayMode: 'full-detail' },
  inspectArchiveEntries: { label: '查看压缩包' },
  readAttachmentText: { label: '读取附件' },
  readArchiveEntryText: { label: '读取包内文件' },
  bundleArchiveEntries: { label: '重打包压缩包文件' },
  bundleAttachments: { label: '打包附件' },
  createQrCode: { label: '生成二维码' },
  generateImage: { label: '生成图片' },
  sendImageAttachment: { label: '发送图片' },
  inspectImageAsset: { label: '检查图片素材' },
  extractImagePalette: { label: '提取图片配色' },
  createImageVariant: { label: '生成图片素材' },
  saveAttachmentToCollection: { label: '存入图片收藏' },
  saveAttachmentAsCodeCard: { label: '存成房间' },
  saveArchiveEntryAsCodeCard: { label: '压缩包文件存成房间' },
  runAndroidShell: { label: '运行手机 Shell', group: 'device', resultReplayMode: 'detail-excerpt' },
  runCode: { label: '执行代码', resultReplayMode: 'detail-excerpt' },
  listDesktopWorkspaces: { label: '读取本机工作区', group: 'desktop', resultReplayMode: 'full-detail' },
  listDesktopFiles: { label: '读取本机目录', group: 'desktop', resultReplayMode: 'full-detail' },
  readDesktopFile: { label: '读取本机文件', group: 'desktop', resultReplayMode: 'full-detail' },
  searchDesktopFiles: { label: '搜索本机文件', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  readDesktopFileContext: { label: '读取本机文件上下文', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  writeDesktopFile: { label: '写入本机文件', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  editDesktopFileText: { label: '局部替换本机文件', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  replaceDesktopFileLines: { label: '按行替换本机文件', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  createDesktopDirectory: { label: '创建本机文件夹', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  deleteDesktopPath: { label: '删除本机路径', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  moveDesktopPath: { label: '移动本机路径', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  runDesktopCommand: { label: '运行本机命令', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  runDesktopCommandSequence: { label: '运行本机命令流程', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  startDesktopCommand: { label: '启动本机终端会话', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  listDesktopCommandSessions: { label: '查看本机终端会话', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  stopDesktopCommand: { label: '停止本机终端会话', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  syncDesktopWorkspaceFromDisk: { label: '从电脑读入工作区', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  syncDesktopWorkspaceToDisk: { label: '送到电脑工作区', group: 'desktop', resultReplayMode: 'detail-excerpt' },
  invokeCodeCardTool: { label: '调用房间工具', group: 'card', resultReplayMode: 'detail-excerpt' },
  invokeMcpTool: { label: '调用 MCP 工具', group: 'mcp', resultReplayMode: 'full-detail' }
};

export function resolveToolExecutorPluginId(kind: ToolActionKind): PolarisToolExecutorPluginId {
  return POLARIS_TOOL_EXECUTOR_BY_ACTION_KIND[kind];
}

export function isToolActionKindHandledByPlugin(
  kind: ToolActionKind,
  pluginId: PolarisToolExecutorPluginId
) {
  return resolveToolExecutorPluginId(kind) === pluginId;
}
